name: Secutils Web UI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'config/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '*.md'
      - '.husky/**'

jobs:
  ci:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
